name: Demo

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint:
    name: Lint
    runs-on: macos-26

    steps:
      - uses: actions/checkout@v4
      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '26'
      - name: Install SwiftFormat
        run: brew install swiftformat
      - name: SwiftFormat Check
        run: swiftformat . --lint
      - name: Install SwiftLint
        run: brew install swiftlint
      - name: Generate Compiler Log
        run: |
          set -o pipefail
          swift build --build-tests -v > swift-build.log 2>&1
      - name: SwiftLint
        run: swiftlint --strict --config .swiftlint.yml
      - name: SwiftLint Analyze
        run: swiftlint analyze --strict --config .swiftlint.yml --compiler-log-path swift-build.log

  build:
    name: Build
    runs-on: macos-26
    needs: lint

    steps:
      - uses: actions/checkout@v4
      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '26'
      - name: Build
        run: xcodebuild -project ./Demo/Demo.xcodeproj -scheme Demo -destination 'platform=iOS Simulator,name=iPhone 17,OS=latest' clean build
